### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by JoeBSong** [ideinteractive/simple-logo-carousel#1]
Able to post negative numbers for Slides to Show and Slides to Scroll

**Comment by JoeBSong** [comment]
This also applies to these in Carousel Options: Speed, Autoplay Speed, Hover Text Background Opacity, and Arrow Image Max Width. The first three resets to default but not the last one - Arrow Image Max Width

**Comment by JoeBSong** [comment]
Also for Arrow Size, Arrow Offset

**Comment by tvledesign** [comment]
Slides to Show and Slide to Scroll can't go to negative or 0. Default is always 1 (minimum I should say)
Autoplay speed, speed can't go to negative or 0 either.
Opacity min is 0 and max is 1 and can only go up by 0.1 increments at a time.

Arrow image max width should reset back to default 50px and it can be negative because this isn't a number but a string.

Please confirm other fixes.

**Comment by JoeBSong** [comment]
Arrow Size  still can go negative and doesn't go back to default upon default, as well as Slides to Show and Slides to Scroll

**Comment by tvledesign** [comment]
Arrow Size can go into negative because it's a text field not a number field. But Show and Slides to Scroll should be fixed.

**Comment by JoeBSong** [comment]
Confirmed fixed
